try {
    nonExistentFunction();
}
catch{
   throw ' errorgh ';
}